Traceback (most recent call last):
  File "code/eval_model.py", line 45, in <module>
    net.load_state_dict(checkpoint["state_dict"])
  File "/net/projects/scratch/summer/valid_until_31_January_2021/sgroen/miniconda/envs/torch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 830, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for ConvSame_3_net:
	Missing key(s) in state_dict: "conv1.weight", "conv1.bias", "conv2.weight", "conv2.bias", "conv3.weight", "conv3.bias". 
	Unexpected key(s) in state_dict: "init_conv.conv1.weight", "init_conv.conv1.bias", "init_conv.conv2.weight", "init_conv.conv2.bias", "down1.conv_block.conv1.weight", "down1.conv_block.conv1.bias", "down1.conv_block.conv2.weight", "down1.conv_block.conv2.bias", "down2.conv_block.conv1.weight", "down2.conv_block.conv1.bias", "down2.conv_block.conv2.weight", "down2.conv_block.conv2.bias", "down3.conv_block.conv1.weight", "down3.conv_block.conv1.bias", "down3.conv_block.conv2.weight", "down3.conv_block.conv2.bias", "up3.conv_trans1.weight", "up3.conv_trans1.bias", "up3.conv_block.conv1.weight", "up3.conv_block.conv1.bias", "up3.conv_block.conv2.weight", "up3.conv_block.conv2.bias", "up2.conv_trans1.weight", "up2.conv_trans1.bias", "up2.conv_block.conv1.weight", "up2.conv_block.conv1.bias", "up2.conv_block.conv2.weight", "up2.conv_block.conv2.bias", "up1.conv_trans1.weight", "up1.conv_trans1.bias", "up1.conv_block.conv1.weight", "up1.conv_block.conv1.bias", "up1.conv_block.conv2.weight", "up1.conv_block.conv2.bias", "out.weight", "out.bias". 

Lavish subscription of memory-resources:

	8192 Mbytes requested,
	but peak usage was only 2948.2 Mbytes.

------------> Please request grid resources more carefully! <------------

